<a href="https://colab.research.google.com/github/nimnathw/linear-algebra-with-python/blob/main/linea_algebra_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercise: Exploring Vector Direction and Magnitude

Instructions:

Consider the following two 3-dimensional vectors:

1. Vector v⃗:
   v⃗ = (3, 4, 2)

2. Vector u⃗:
   u⃗ = (1, 2, 5)

Perform the following operations:

1. Compute the magnitude of each vector using the Euclidean norm formula.
2. Calculate the direction of each vector.
3. Find the vector v⃗ - u⃗ and u⃗ - v⃗.
4. Compute the sum, u⃗ + v⃗.
5. Draw the vectors v⃗ and u⃗ as arrows in a 3-dimensional space using Matplotlib.
6. Draw the resulting vectors v⃗ - u⃗, u⃗ - v⃗, and u⃗ + v⃗ in the same 3-dimensional space using Matplotlib.

Requirements:

1. Utilize the NumPy library for vector calculations and operations.
2. Use Matplotlib for creating visual representations of the vectors in a 3-dimensional space.
3. Clearly present each step of the calculations and operations.
4. Explain the significance of the results in the context of vector operations and their applications in real-world scenarios.






# Exercise: Exploring Dot Product
Instructions:

Consider the following two 3-dimensional vectors:

1. Vector v⃗:
   v⃗ = [3, 4, 2]

2. Vector w⃗:
   w⃗ = [1, 2, 5]

Perform the following steps:

1. Utilize the NumPy library to calculate the dot product of vectors v⃗ and w⃗.
2. Compute the magnitudes of vectors v⃗ and w⃗ using appropriate NumPy functions.
3. Determine the angle θ between the two vectors using the inverse cosine function in NumPy.
4. Verify that the dot product v⃗ ⋅ w⃗ is equal to the product of the magnitudes of v⃗ and w⃗ multiplied by cos θ, using NumPy calculations.
5. Create a 3D plot using Matplotlib to visualize the vectors v⃗ and w⃗ as arrows in a 3-dimensional space.
6. Label the plot to represent the vectors and the angle θ between them.

Requirements:

1. Use the NumPy library for vector calculations, including the dot product, magnitude calculation, and angle determination.
2. Utilize Matplotlib to create a 3D plot representing the vectors and the angle between them.
3. Provide a step-by-step explanation of the calculations and the code used for visualization.
4. Discuss the significance of the dot product, the computed angle, and the visualization in understanding the relationship between vectors.



# Exercise Title: Exploring Cross Product

Instructions:

Consider the following two 3-dimensional vectors:

1. Vector v⃗:
   v⃗ = [3, 4, 2]

2. Vector w⃗:
   w⃗ = [1, 2, 5]

Perform the following steps:

1. Use the NumPy library to compute the cross product of vectors v⃗ and w⃗.
2. Interpret the geometric meaning of the cross product in terms of vector perpendicularity and the area of the parallelogram formed by the two vectors.
3. Calculate the magnitude of the cross product and explain how it relates to the area of the parallelogram.
4. Visualize the vectors v⃗ and w⃗ along with their cross product using Matplotlib in a 3-dimensional space.
5. Discuss the implications of the right-hand rule in determining the direction of the resulting vector in the cross product.

Requirements:

1. Utilize the NumPy library for vector calculations, especially for the cross product and magnitude computation.
2. Use Matplotlib to create a 3D plot representing the vectors and the resulting cross product.
3. Provide a step-by-step explanation of the calculations and the code used for visualization.
4. Discuss the significance of the cross product, its geometric interpretation, and its practical applications in diverse fields.


# Exercise: Calculating the Area of a 3D Triangle Using Cross Product

Instructions:

Consider a triangle formed by three points in 3D space: A(2, 3, 1), B(4, 1, 2), and C(5, 3, 6). Perform the following steps:

1. Compute the vectors $\vec {AB}$ and $\vec {AC}$ using the given coordinates.
2. Calculate the cross product of vectors $\vec {AB}$ and $\vec {AC}$ using the cross product formula.
3. Determine the magnitude of the resulting cross product vector $\vec {n}$ using the magnitude formula provided.
4. Divide the magnitude of $\vec {n}$ by 2 to obtain the area of the triangle.
5. Discuss the significance of the computed area and how it relates to the orientation of the triangle in 3D space.
6. Illustrate the triangle and the vectors $\vec {AB}$ and $\vec {AC}$ in a 3D coordinate system using Matplotlib to provide a visual representation.



# Exercise: Computing the Volume of a Parallelepiped

Instructions:

Consider a parallelepiped formed by three non-coplanar vectors in 3D space: **u** = [1, 2, 3], **v** = [4, 1, 2], and **w** = [2, 3, 5]. Perform the following steps:

1. Create a 3x3 matrix using the components of vectors **u**, **v**, and **w** as the rows or columns of the matrix.
2. Compute the determinant of the 3x3 matrix using the provided determinant formula.
3. Determine the absolute value of the determinant, which represents the volume of the parallelepiped spanned by vectors **u**, **v**, and **w**.
4. Discuss the significance of the computed volume and its relation to the orientation and shape of the parallelepiped in 3D space.
5. Illustrate the parallelepiped defined by vectors **u**, **v**, and **w** in a 3D coordinate system using Matplotlib for visual representation.

Requirements:

1. Apply the determinant formula accurately using the components of vectors **u**, **v**, and **w** to compute the volume of the parallelepiped.
2. Provide a clear explanation of the process involved in calculating the determinant and its interpretation as the volume of the parallelepiped.
3. Create a 3x3 matrix and compute the determinant using the provided components of vectors **u**, **v**, and **w**.
4. Explain the relevance of determinants in linear algebra and their applications in calculating the volume of parallelepipeds in 3D space.

# Exercise: Prove the formula for the projection of a vector

Prove the formula for the projection of a vector $u$ onto another vector $w$, i.e., $\text{proj}_w (u) = \frac{u \cdot w}{w \cdot w} \cdot w$.


**Hint:**
Use the definition of the dot product to express $u \cdot w$ in terms of the magnitudes of vectors $u$ and $w$ and the cosine of the angle between them, $u \cdot w = \|u\| \|w\| \cos(\theta)$.


### Common MathJax/LaTeX Commands

**Basic Formatting Commands:**
1. *Italic Text*: \textit{your text}.
2. **Bold Text**: \textbf{your text}.
3. Underline Text: \underline{your text}.
4. Subscript: x\_{sub} for subscript.
5. Superscript: x^{sup} for superscript.
6. Space: \quad for space.


**Vectors and Matrices:**
1. Vector: \mathbf{v} for boldface vectors.
2. Matrix: \mathbf{A} for boldface matrices.
3. Transpose: \mathbf{A}^\text{T} for transpose of matrix A.
4. Determinant: \text{det}(A) for the determinant of matrix A.
5. Inverse: A^{-1} for the inverse of matrix A.

**Operators and Symbols:**
1. Dot Product: \cdot for dot product of vectors.
2. Hadamard product (element-wise multiplication of two matrices with the same dimensions): \odot

if you have two matrices $A$ and $B$ of the same size, the element-wise multiplication is denoted as $C = A \odot B$, where each element $C_{ij}$ is the product of the corresponding elements $A_{ij}4 and $B_{ij}$.

3. Cross Product: \times for cross product of vectors.
4. Scalar Multiplication: k\mathbf{v} for scalar multiplication.
5. Summation: \sum_{i=1}^{n} for summation.
6. Product: \prod_{i=1}^{n} for product.

**Equations and Formulas:**
1. Inline Equation: *dollar sign* your equation  *dollar sign* for inline equations.
2. Display Equation: *dollar sign* *dollar sign* your equation *dollar sign* *dollar sign* for displayed equations.
3. Fractions: \frac{numerator}{denominator} for fractions.
4. Square Root: \sqrt{x} for square root.
5. Parentheses and Brackets: (, ), [, ], \{, \}, \left(, \right), \left[, \right], \left\{, \right\} for different types of parentheses and brackets.

**Trigonometric Functions:**
1. Sine: \sin(x) for sine of x.
2. Cosine: \cos(x) for cosine of x.
3. Tangent: \tan(x) for tangent of x.

**Calculus:**
1. Derivative: \frac{d}{dx} for derivative with respect to x.
2. Integral: \int_{a}^{b} for definite integral from a to b.


# Exercise: Vector Decomposition and Visualization (1)

Consider two 2-dimensional vectors: $ u = [3, 4] $ and $ w = [1, 2] $.

1. Calculate the dot product of the two vectors $u$ and $w$ using the provided formula. Find the magnitude of $u$, the magnitude of $w$, and the angle $\theta$ between the two vectors.

2. Compute the projection of vector $u$ onto vector $w$ using the formula $||u|| \cos(\theta)$.

3. Decompose vector $u$ into components along vector $w$ using the formula for projection $\text{proj}_w(u) = \frac{u \cdot w}{w \cdot w} \cdot w$.

4. Find the component of vector $u$ orthogonal to $w$ using the formula $u_{\perp} = u - \text{proj}_w(u)$.

5. Use NumPy to perform the calculations and visualize the results with Matplotlib. Plot the original vectors, the projection of $u$ onto $w$, and the component of $u$ orthogonal to $w$ on a 2D plane.


# Exercise: Vector Decomposition and Visualization (2)

Consider two 2-dimensional vectors: $ u = [3, 4] $ and $ w = [1, 0] $.

1. Compute the projection of vector $u$ onto vector $w$.

2. Find the component of vector $u$ orthogonal to $w$.

3. Use NumPy to perform the calculations and visualize the results with Matplotlib. Plot the original vectors, the projection of $u$ onto $w$, and the component of $u$ orthogonal to $w$ on a 2D plane.

# Exercise: Vector Decomposition and Visualization (3)

Consider two 2-dimensional vectors: $ u = [3, 4] $ and $ w = [0, 6] $.

1. Compute the projection of vector $u$ onto vector $w$.

2. Find the component of vector $u$ orthogonal to $w$.

3. Use NumPy to perform the calculations and visualize the results with Matplotlib. Plot the original vectors, the projection of $u$ onto $w$, and the component of $u$ orthogonal to $w$ on a 2D plane.

# Excercise: Equation of a Line (1)

Consider the point P(7, 4, -1) and a vector v = (1, 3, 4).

1. Find the parametric equations for the line passing through the point P and parallel to the vector v.

2. Visualize the line using NumPy and Matplotlib. You can use the `matplotlib.pyplot` and `mpl_toolkits.mplot3d` modules for 3D plotting.


**Hint:**
Remember that the parametric equation for a line in 3D space is of the form:

$$x = x_0 + at$$
$$y = y_0 + bt$$
$$z = z_0 + ct$$

where (x0, y0, z0) is a point on the line, and (a, b, c) are the direction ratios of the line.




# Exercise: Equation of a Line (2)
Consider the following two lines in 3D space:

Line 1:
$$\frac{x - 2}{2} = \frac{y - 3}{1} = \frac{z - 1}{4}$$

Line 2:
$$\frac{x - 4}{3} = \frac{y - 2}{2} = \frac{z - 3}{5}$$

1. Do the lines intersect or are they skewed?.
2. Use NumPy and Matplotlib to plot the two lines. You can use the `matplotlib.pyplot` and `mpl_toolkits.mplot3d` modules for 3D plotting.

# Exercise: Equation of a Line (3)

Consider the following two lines in 3D space:

Line 1:
$$\frac{x - 5}{3} = \frac{y - 5}{4} = \frac{z - 5}{2}$$

Line 2:
$$\frac{x - 11}{4} = \frac{y - 3}{2} = \frac{z - 7}{2}$$

1. Find the point of intersection, \(P\), of these two lines.
2. Use NumPy and Matplotlib to plot the two lines and the point of intersection in 3D space. You can use the `matplotlib.pyplot` and `mpl_toolkits.mplot3d` modules for 3D plotting.

# Exercise: Equation of a Line (4)

Consider the following parametric equation for a line in 5-d space:

$$x_1 = a_1 + t \cdot d_1,$$
$$x_2 = a_2 + t \cdot d_2,$$
$$x_3 = a_3 + t \cdot d_3,$$
$$x_4 = a_4 + t \cdot d_4,$$
$$x_5 = a_5 + t \cdot d_5,$$

where:
- $a_1, a_2, a_3, a_4, a_5$ are constants representing the starting points along each dimension,
- $d_1, d_2, d_3, d_4, d_5$ are the direction vectors along each dimension,
- $t$ is the parameter that determines the position of points along the line.

Line 1 is:
$$a = (1, 2, 3, 4, 5),$$
$$d = (2, 3, 1, 4, 2),$$

Line 2 is:
$$a = (7, -4, 9, 14, 1),$$
$$d = (2, 3, 1, 4, 2),$$

1. Find the shortest distance between these two parallel lines.
2. Use numpy code to calculate and print out the shortest distance between the two lines.


# Exercise: Equation of a Line (5)

Consider the following parametric equation for a line in 5-d space:

$$x_1 = a_1 + t \cdot d_1,$$
$$x_2 = a_2 + t \cdot d_2,$$
$$x_3 = a_3 + t \cdot d_3,$$
$$x_4 = a_4 + t \cdot d_4,$$
$$x_5 = a_5 + t \cdot d_5,$$

where:
- $a_1, a_2, a_3, a_4, a_5$ are constants representing the starting points along each dimension,
- $d_1, d_2, d_3, d_4, d_5$ are the direction vectors along each dimension,
- $t$ is the parameter that determines the position of points along the line.

Line 1 is:
$$a = (1, 2, 3, 4, 5),$$
$$d = (2, 3, 1, 4, 2),$$

Point P is:
$$ P = (18, -6, 3, 14, 1)$$

1. Find the shortest distance between the point P and Line 1.
2. Use numpy code to calculate and print out the shortest distance.


# Exercise: Equation of a Line (6)

Consider the following parametric equation for a line in 3-d space:

$$x_1 = a_1 + t \cdot d_1,$$
$$x_2 = a_2 + t \cdot d_2,$$
$$x_3 = a_3 + t \cdot d_3,$$

where:
- $a_1, a_2, a_3 are constants representing the starting points along each dimension,
- $d_1, d_2, d_35$ are the direction vectors along each dimension,
- $t$ is the parameter that determines the position of points along the line.

Line 1 is:
$$a = (4, 2, 3),$$
$$d = (6, 3, 1),$$

Point P is:
$$ P = ( 5, 1, 7)$$

1. Find the shortest distance between the point P and Line 1 using two methods.
2. Use numpy code to  and print out the shortest distance.


# Exercise: Standard Form of Plane Equation (1)

Consider a plane parallel to $2x - 4y + 3z = 10$ and passing through the point $Q(1, -2, 4)$.

1. Find the standard form of the plane equation.
2. Use NumPy and Matplotlib to plot the plane.




# Exercise: Standard Form of a Plane Equation (2)

Consider a plane parallel to $5x - 3y + 2z = 12$ and passing through the point $Q(2, -1, 3)$.

1. Find the standard form of the plane equation.
2. Use NumPy and Matplotlib to plot the plane.


# Exercise: Standard Form of Plane Equation (3)

1. What do the coefficients A, B, and C represent in the standard form of a plane equation, and how are they related to the geometry of the plane?

2. Explain the significance of the constant term D in the standard form of the plane equation, and how does it relate to the distance of the plane from the origin along the direction of the normal vector?

3. Discuss the role of the Euclidean norm of the normal vector in the formula for calculating the distance of the plane from the origin. How does it ensure that the distance is independent of the magnitudes of the coefficients A, B, and C?

4. What does the special case of the plane equation in the form Ax + By + Cz = 0 signify? How does the value of the constant term D influence the position of the plane in this case?

5. Consider two planes with the same normal vector $\langle A, B, C \rangle$ but different constants $D_1$ and $D_2$. Discuss the parallelism and orientation of these planes in space. Calculate the distance between the two parallel planes and explain its significance in the context of the plane geometry.


# Exercise: Standard Form of Plane Equation (4)

1. For the plane defined by the equation $4x - 2y + 3z = 8$, determine the components of the normal vector and the distance of the plane from the origin along the direction of the normal vector.

2. Consider a plane with the equation $2x + 3y - 5z = 12$. Calculate the Euclidean norm of the normal vector and explain its significance in terms of the distance of the plane from the origin.

3. Find the equation of the plane passing through the origin and having a normal vector $\langle 1, -3, 2 \rangle$.

4. Given two parallel planes with the equations $3x + 2y - 4z = 10$ and $3x + 2y - 4z = 5$ respectively, calculate the distance between these two planes along the direction of their common normal vector. Plot the two planes using Numpy and Matplotlib.



# Exercise: Standard Form of Plane Equation (5)

1. For the plane defined by the equation $3x - y + 5z = 18$, determine the components of the normal vector and the distance of the plane from the origin along the direction of the normal vector.

2. Consider a plane with the equation $7x + 2y - 3z = 12$. Calculate the Euclidean norm of the normal vector and explain its significance in terms of the distance of the plane from the origin.

3. Find the equation of the plane passing through the origin and having a normal vector $\langle 3, -4, 2 \rangle$.

4. Given two parallel planes with the equations $4x + 3y - 2z = 15$ and $4x + 3y - 2z = -25$ respectively, calculate the distance between these two planes along the direction of their common normal vector. Plot the two planes using Numpy and Matplotlib.

# Exercise: Converting a Plane Equation from Standard Form to Parametric Form (1)

Consider the plane with the equation $3x - 4y + 2z = 5$.

1. Find the parametric form of this plane equation.

2. Plot the plane using numpy and matplotlib.




# Exercise: Converting a Plane Equation from Standard Form to Parametric Form (2)

Consider the plane with the equation $7x + 2y + z = -5$.

1. Find the parametric form of this plane equation.

2. Plot the plane using numpy and matplotlib.

# Exercise: Converting a Plane Equation from Standard Form to Parametric Form (3)

Consider the plane with the equation $ -6x + y + 7z = -12$.

1. Find the parametric form of this plane equation.

2. Plot the plane using numpy and matplotlib.

# Exercise: Converting a Plane Equation from Parametric Form to Standard Form (1)

Consider the  plane equation:

$$P(s, t) = P_0 + s\mathbf{v} + t\mathbf{w}$$


where $P_0 = (1,0-2)$ is a point on the plane, $\mathbf{v} = (1,3,6)$ and $\mathbf{w} = (4,-7,2)$ vectors on the plane, and $s$ and $t$ are parameters.


1. Find the standard form of this plane equation.

2. Plot the plane using numpy and matplotlib.

# Exercise: Converting a Plane Equation from Parametric Form to Standard Form (2)

Consider the  plane equation:

$$P(s, t) = P_0 + s\mathbf{v} + t\mathbf{w}$$


where $P_0 = (11,2,7)$ is a point on the plane, $\mathbf{v} = (3,-2,4)$ and $\mathbf{w} = (7,-6,3)$ vectors on the plane, and $s$ and $t$ are parameters.


1. Find the standard form of this plane equation.

2. Plot the plane using numpy and matplotlib.

# Exercise: Converting a Plane Equation from Parametric Form to Standard Form (3)

Consider the  plane equation:

$$P(s, t) = P_0 + s\mathbf{v} + t\mathbf{w}$$

where $P_0 = (-8,12,7)$ is a point on the plane, $\mathbf{v} = (4,-5,3)$ and $\mathbf{w} = (1,3,2)$ vectors on the plane, and $s$ and $t$ are parameters.


1. Find the standard form of this plane equation.

2. Plot the plane using numpy and matplotlib.

# Exercise: Finding the Plane Equation from 3 Points (1)

Consider the points $Q(1, 2, 3)$, $R(5,6,2)$, and $S(7, 11, 4)$.

1. Find the standard form of the plane that goes through the three points.
2. Use numpy and matplotlib to draw the plane and the points.


# Exercise: Finding the Plane Equation from 3 Points (2)

Consider the points $Q(11, 4, 5)$, $R(3,1,2)$, and $S(5, 3, 4)$.

1. Find the standard form of the plane that goes through the three points.
2. Use numpy and matplotlib to draw the plane and the points.

# Exercise: Finding the Plane Equation from 3 Points (3)

Consider the points $Q(-6, 14, 7)$, $R(2,1,7)$, and $S(-5, 1, 6)$.

1. Find the standard form of the plane that goes through the three points.
2. Use numpy and matplotlib to draw the plane and the points.

#Exercise: Distance between a Point and a Plane in 3D Space (1)

Let $ \mathbf{P} $ and $ \mathbf{Q} $ be two points in 3D space, and let $ \vec{\mathbf{n}} $ be the normal vector of the plane passing through the point $ \mathbf{Q} $ on the plane.

Prove that the distance from the point $ \mathbf{P} $ to this plane is:

$
\text{distance} = \frac{| \vec (\mathbf{P} - \mathbf{Q}) \cdot \vec{\mathbf{n}}|}{\|\vec{\mathbf{n}}\|}
$

where $ \cdot $ denotes the dot product and $ \|\mathbf{n}\| $ denotes the magnitude of the vector $ \vec{\mathbf{n}} $. This formula represents the magnitude of the projection of the vector $ \mathbf{QP} $ onto the direction of the normal vector $ \mathbf{n} $.

#Exercise: Distance between a Point and a Plane in 3D Space (2)

Consider the following points in 3D space:

- $\mathbf{P} (3, 4, 5)$
- $\mathbf{Q} (1, 2, 3)$

Let $\vec{\mathbf{n}} = \langle 2, -1, 4 \rangle$ be the normal vector of the plane passing through the point $\mathbf{Q}$ on the plane..

1. Calculate the distance from the point $\mathbf{P}$ to the plane passing through $\mathbf{Q}$.

2. Plot the points $\mathbf{P}$ and $\mathbf{Q}$ in 3D space along with the plane passing through $\mathbf{Q}$ using NumPy and Matplotlib.


#Exercise: Distance between a Point and a Plane in 3D Space (3)

Consider the following points in 3D space:

- $\mathbf{P} (-7, 2, 3)$
- $\mathbf{Q} (5, 7, -3)$

Let $\vec{\mathbf{n}} = \langle 3, 1, 2 \rangle$ be the normal vector of the plane passing through the point $\mathbf{Q}$ on the plane.

1. Calculate the distance from the point $\mathbf{P}$ to the plane passing through $\mathbf{Q}$.

2. Plot the points $\mathbf{P}$ and $\mathbf{Q}$ in 3D space along with the plane passing through $\mathbf{Q}$ using NumPy and Matplotlib.


#Exercise: Distance between a Point and a Plane in 3D Space (4)

Consider the following points in 3D space:

- $\mathbf{P} (11, 2, 7)$
- $\mathbf{Q} (-4, 3, 2)$

Let $\vec{\mathbf{n}} = \langle 5, -2, 3 \rangle$ be the normal vector of the plane passing through the point $\mathbf{Q}$.

1. Calculate the distance from the point $\mathbf{P}$ to the plane passing through $\mathbf{Q}$ on the plane.

2. Plot the points $\mathbf{P}$ and $\mathbf{Q}$ in 3D space along with the plane passing through $\mathbf{Q}$ using NumPy and Matplotlib.

# Exercise: Distance between two Parallel Planes (1)

Consider the two planes are defined by the equation $Ax+By+Cz=D_1$ and $Ax+By+Cz=D_2$, where $A=3$, $B=-4$, and $C=2$ are the coefficients of the normal vector to the plane, and $D_1 = -7$ and $D_2 =8$.

1. Find the Euclidean distance between the two planes.
2. Plot the two plane using numpy and matplotlib.


# Exercise: Distance between two Parallel Planes (2)

Consider the two planes are defined by the equation $Ax+By+Cz=D_1$ and $Ax+By+Cz=D_2$, where $A=-5$, $B=7$, and $C=1$ are the coefficients of the normal vector to the plane, and $D_1 = 15$ and $D_2 = -34$.

1. Find the Euclidean distance between the two planes.
2. Plot the two plane using numpy and matplotlib.

# Exercise: Distance between two Parallel Planes (3)

Consider the two planes are defined by the equation $Ax+By+Cz=D_1$ and $Ax+By+Cz=D_2$, where $A=8$, $B=-9$, and $C=4$ are the coefficients of the normal vector to the plane, and $D_1 = 0$ and $D_2 = -12$.

1. Find the Euclidean distance between the two planes.
2. Plot the two plane using numpy and matplotlib.

# Exercise: Distance from a Plane to a Point when the Plane Equation is given (1)

A plane is defined by the equation $Ax+By+Cz=D$, where $A$, $B$, and $C$ are the coefficients of the plane's normal vector.

Now, suppose we have a point $P(x_1, y_1, z_1)$ in the 3D space.

Prove that the distance between this point and the plane is:

$$ \text{Distance} = \frac{|Ax_1+By_1+Cz_1-D|}{\sqrt{A^2+B^2+C^2}} $$

# Exercise: Distance from a Plane to a Point when the Plane Equation is given (2)

A plane is defined by the equation $Ax+By+Cz=D$, where $A=1$, $B=2$, and $C=3$ are the coefficients of the plane's normal vector, and $D=12$.

Consider a point $P(-5, 1, 2)$ in the 3D space.
1. Find the distance between the point P and the plane.
2. Plot the point P and plane using numpy and matplotlib.

# Exercise: Distance from a Plane to a Point when the Plane Equation is given (3)

A plane is defined by the equation $Ax+By+Cz=D$, where $A=1$, $B=2$, and $C=3$ are the coefficients of the plane's normal vector, and $D=12$.

Consider a point $P(-3, 0, 2)$ in the 3D space.
1. Find the distance between the point P and the plane.
2. Plot the point P and plane using numpy and matplotlib.

# Exercise: Distance from a Plane to a Point when the Plane Equation is given (4)

A plane is defined by the equation $Ax+By+Cz=D$, where $A=1$, $B=2$, and $C=3$ are the coefficients of the plane's normal vector, and $D=12$.

Consider a point $P(-4, 2, 4)$ in the 3D space.
1. Find the distance between the point P and the plane.
2. Plot the point P and plane using numpy and matplotlib.

# Exercise: Angle between Planes (1)

Consider two planes, each defined by the equations $A1x + B1y + C1z = D1$ and $A2x + B2y + C2z = D2$.

Prove that the cosine of the angle $(\theta)$ between the two planes is:

   $$ \cos(\theta) = \frac{|n1 \cdot n2|}{\|n1\| \|n2\|} $$

where, $n1 = \langle A1, B1, C1 \rangle$ and $n2= \langle A2, B2, C2 \rangle$ represent the corresponding normal vectors to the planes, $|n1 \cdot n2|$ represents the absolute value of the dot product of the normal vectors, and $||n1||$ and $||n2||$ represent the magnitudes of the respective normal vectors.

Hint: Draw the two planes and the corresponding normal vectors to visualize $\theta$.

# Exercise: Angle between Planes (2)

Consider two planes, each defined by the equations $3x + 4y - 5z = 11$ and $3x + 4y - 5z = -16$.

1. Find the angle between two planes.
2. Draw the two planes using numpy and matplotlib.

# Exercise: Angle between Planes (3)

Consider two planes, each defined by the equations $3x + 4y - 5z = 11$ and $5x + 9y - 4z = 6$.

1. Find the angle between two planes.
2. Draw the two planes using numpy and matplotlib.

# Exercise: Angle between Planes (4)

Consider two planes, each defined by the equations $7x + y -35z = 0$ and $x + 5y - 3z = 6$.

1. Find the angle between two planes.
2. Draw the two planes using numpy and matplotlib.

# Exercise: Linear Dependence (1)

Consider the following three 3D vectors:

$v_1 = \langle 1, 2, 3 \rangle,$
$v_2 = \langle 2, 1, 4 \rangle,$
$v_3 = \langle 3, 3, 7 \rangle$

1. Determine whether the vectors $v_1$, $v_2$, and $v_3$ are linearly independent or linearly dependent. If they are linearly dependent, express one of the vectors as a linear combination of the others.
2. Use NumPy and Matplotlib to draw the vectors in 3D space.

# Exercise: Linear Dependence (2)

Consider the following three 2D vectors:

$v_1 = \begin{bmatrix} 1 \\ 2 \end{bmatrix}$
$v_2 = \begin{bmatrix} 2 \\ 1 \end{bmatrix}$
$v_3 = \begin{bmatrix} 3 \\ 3 \end{bmatrix}$

1. Determine whether the vectors $v_1$, $v_2$, and $v_3$ are linearly independent or linearly dependent. If they are linearly dependent, express one of the vectors as a linear combination of the others.
2. Use NumPy and Matplotlib to draw the vectors in 2D space.
3. Is it possible to have three linearly independent vectors in 2D space?


# Exercise: Linear Dependence (3)

Consider the following three 5D vectors:

$v_1 = [1, 2, 3, 4, 5],$
$v_2 = [2, 1, 4, 3, 6],$
$v_3 = [3, 3, 7, 2, 8]$

Determine whether the vectors $v_1, v_2, v_3$ are linearly independent or linearly dependent. If they are linearly dependent, find the linear combination of the vectors that represents one of the vectors.


# Exercise: Gaussian Elimination (1)

1. Write the steps of Gausian Elimination in natural language.
2. Write a Python function using NumPy that performs the row echelon form (REF) algorithm on a given matrix. Assume that the input matrix is a NumPy array. The function should take the matrix as an argument and return the resulting matrix in row echelon form.
3. Test for accuracy of the function by printing out the REF matrix of two matrices.

**Hint**: If the pivot is zero, find a non-zero element below in the same column for row swapping.

# Exercise: Gaussian Elimination (2)

Consider the following augmented matrix:

$$
\left[\begin{array}{ccc|c}
1 & 2 & 3 & 10 \\
2 & 5 & 2 & 14 \\
3 & 1 & 4 & 12
\end{array}\right]
$$

Perform the necessary row operations to transform this augmented matrix into row echelon form (REF). Then, state the resulting matrix in REF.



# Exercise: Gaussian Elimination (3)

Consider the following augmented matrix:

$$
\left[\begin{array}{ccc|c}
4 & 2 & -3 & 2 \\
-1 & 3 & 2 & 4 \\
2 & 1 & 3 & 6
\end{array}\right]
$$

Perform the necessary row operations to transform this augmented matrix into row echelon form (REF). Then, state the resulting matrix in REF.



# Exercise: Gaussian Elimination (4)

Consider the following augmented matrix:

$$
\left[\begin{array}{ccc|c}
2 & 4 & 6 & 8 \\
1 & 3 & 5 & 7 \\
-1 & -2 & -3 & -4
\end{array}\right]
$$

Perform the necessary row operations to transform this augmented matrix into row echelon form (REF). Then, state the resulting matrix in REF.

# Gauss-Jordan elimination (1)
1. Write the steps of Gausian-Jordan elimination in natural language.
2. Write a Python function using NumPy that performs the row echelon form (RREF) algorithm on a given matrix. Assume that the input matrix is a NumPy array. The function should take the matrix as an argument and return the resulting matrix in row echelon form.
3. Test for accuracy of the function by printing out the RREF matrix of two matrices.

**Hint**: If the pivot is zero, find a non-zero element below in the same column for row swapping.

# Gauss-Jordan elimination (2)

Consider the augmented matrix:

$$ \left( \begin{array}{ccc|c}
1 & 2 & 3 & 4 \\
2 & 3 & 4 & 5 \\
3 & 4 & 5 & 6
\end{array} \right) $$

Find the RREF form using the Gauss-Jordan elimination algorithm.


# Gauss-Jordan elimination (3)

Consider the augmented matrix:

$$ \left( \begin{array}{ccc|c}
3 & 2 & 1 & 4 \\
1 & 2 & 1 & 3 \\
2 & 1 & 2 & 2
\end{array} \right) $$

Determine the reduced row echelon form (RREF) using the Gauss-Jordan elimination method.


# Gauss-Jordan elimination (4)

Consider the augmented matrix:

$$ \left( \begin{array}{ccc|c}
4 & 2 & 1 & 8 \\
2 & 1 & 3 & 5 \\
1 & 3 & 2 & 9
\end{array} \right) $$

Compute the RREF form using the Gauss-Jordan elimination algorithm.

# Exercise: Span (1)

Consider the following set of vectors in a vector space \(V\):

$$v_1 = \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix}, \quad v_2 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}, \quad v_3 = \begin{bmatrix} 1 \\ 1 \\ 2 \end{bmatrix}
$$

1. What is the dimension of the vector space $V$?

2. Determine the span of the set of vectors $v_1, v_2, v_3$.

3. Verify whether the set of vectors $v_1, v_2, v_3$ is linearly independent.

4. Use numpy to find the rank of the matrix $A$.

$$A = \begin{bmatrix} 1 & 0 & 1 \\ 0 & 1 & 1 \\ 1 & 1 & 2 \end{bmatrix}$$




# Exercise: Span (2)

Consider the following set of vectors in a 4-dimensional vector space $V$:

$v_1 = \begin{bmatrix} 1 \\ 0 \\ 1 \\ 2 \end{bmatrix}$, $v_2 = \begin{bmatrix} 2 \\ 1 \\ 0 \\ 1 \end{bmatrix}$, $v_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \\ 2 \end{bmatrix}$

1. Determine the dimension of the vector space $V$.

2. Find the span of the set of vectors $v_1, v_2, v_3$.

3. Verify whether the set of vectors $v_1, v_2, v_3$ is linearly independent.

4. Find a basis for the vector space $V$ using the set of vectors $v_1, v_2, v_3$.

5. Use NumPy to find the rank of the matrix $A$:

$A = \begin{bmatrix} v_1 & v_2 & v_3 \end{bmatrix}$

where $v_1, v_2, v_3$ are the column vectors from the exercise.

# Exercise: Span (3)

Consider the following set of vectors in a 4-dimensional vector space $V$:

$v_1 = \begin{bmatrix} 1 \\ 0 \\ 1 \\ 2 \end{bmatrix}$, $v_2 = \begin{bmatrix} 2 \\ 1 \\ 0 \\ 1 \end{bmatrix}$, $v_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \\ 2 \end{bmatrix}, v_4 = \begin{bmatrix} 3 \\ 1 \\ 1 \\ 5 \end{bmatrix}$

1. Determine the dimension of the vector space $V$.

2. Find the span of the set of vectors $v_1, v_2, v_3, v_4$.

3. Verify whether the set of vectors $v_1, v_2, v_3, v_4$ is linearly independent.

4. Does the set of vectors  $v_1, v_2, v_3, v_4$ span the space $V$?

5. Use NumPy to find the rank of the matrix $A$:

$A = \begin{bmatrix} v_1 & v_2 & v_3 & v_4\end{bmatrix}$

where $v_1, v_2, v_3, v_4$ are the column vectors from the exercise.

# Exercise: Linear Transformation of Vectors(1)

Consider a matrix A given by:
$$ A =
\begin{bmatrix}
1 & 1 & 3 \\
-1 & 3 & 2 \\
0 & 2 & 1
\end{bmatrix}
$$

Perform the following tasks:

1. Calculate the transformation of the standard basis vectors: $\begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$, $\begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}$, and $\begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}$ under the matrix A.
2. Compute the transformation of the general vector $\begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}$ under the matrix A.
3. Visualize the transformation using NumPy and Matplotlib. Plot the original vectors and their transformed counterparts in a 3D coordinate system. Make sure to add axes labels and a legend to differentiate the vectors before and after transformation.




# Exercise: Linear Transformation of Vectors (2)

Consider a matrix B given by:
$$ B =
\begin{bmatrix}
1 & 2 & 3 \\
0 & 1 & 2 \\
-1 & 0 & 1
\end{bmatrix}
$$

Perform the following tasks:

1. Calculate the transformation of the standard basis vectors: $\begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$, $\begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}$, and $\begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}$ under the matrix B.
2. Compute the transformation of the general vector $\begin{bmatrix} 2 \\ 1 \\ 1 \end{bmatrix}$ under the matrix B.
3. Visualize the transformation using NumPy and Matplotlib. Plot the original vectors and their transformed counterparts in a 3D coordinate system. Make sure to add axes labels and a legend to differentiate the vectors before and after transformation.


# Exercise: Linear Transformation of Vectors (3)

Consider a matrix C given by:
$$ C =
\begin{bmatrix}
3 & 1 & 2 \\
-1 & 0 & 2 \\
2 & 2 & 1
\end{bmatrix}
$$

Perform the following tasks:

1. Calculate the transformation of the standard basis vectors: $\begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$, $\begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}$, and $\begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}$ under the matrix C.
2. Compute the transformation of the general vector $\begin{bmatrix} 3 \\ 1 \\ 2 \end{bmatrix}$ under the matrix C.
3. Visualize the transformation using NumPy and Matplotlib. Plot the original vectors and their transformed counterparts in a 3D coordinate system. Make sure to add axes labels and a legend to differentiate the vectors before and after transformation.



# Exercise: Linear Transformation with Linearly Dependent Vectors (1)

Consider the matrix A given by:

$$ A = \begin{bmatrix}
1 & 2  \\
3 & 6  \\
\end{bmatrix}
$$

Perform the following tasks:

1. Calculate the transformation of the standard basis vectors: $\begin{bmatrix} 1 \\ 0 \end{bmatrix}$, and $\begin{bmatrix} 0 \\ 1 \end{bmatrix}$ under the matrix A.
2. Compute the transformation of the general vector $\begin{bmatrix} 1 \\ 1 \end{bmatrix}$ under the matrix A.
3. Explain the implications of the transformation on the vectors and the significance of the linearly dependent set of column vectors in the transformation process.
4. Utilize NumPy to perform the necessary calculations step by step.
5. Visualize the transformation using Matplotlib, plotting the original vectors and their transformed counterparts in a 2D coordinate system. Add labels and a legend to distinguish the vectors before and after transformation.





# Exercise: Linear Transformation with Linearly Dependent Vectors (2)

Consider the matrix A given by:

$$ A = \begin{bmatrix}
1 & 4 & 3 \\
3 & 12 & 9 \\
-1 & -4 & -3
\end{bmatrix}
$$

Perform the following tasks:

1. Calculate the transformation of the standard basis vectors: $\begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$, $\begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}$, and $\begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}$ under the matrix A.
2. Compute the transformation of the general vector $\begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}$ under the matrix A.
3. Explain the implications of the transformation on the vectors and the significance of the linearly dependent set of column vectors in the transformation process.
4. Utilize NumPy to perform the necessary calculations step by step.
5. Visualize the transformation using Matplotlib, plotting the original vectors and their transformed counterparts in a 3D coordinate system. Add labels and a legend to distinguish the vectors before and after transformation.





# Exercise: Linear Transformation with Linearly Dependent Vectors (3)

Consider the matrix A given by:

$$ A = \begin{bmatrix}
2 & 1 & 3 \\
-2 & 4 & 2 \\
1 & 3 & 4
\end{bmatrix}
$$

Perform the following tasks:

1. Compute the transformation of the standard basis vectors: $\begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$, $\begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}$, and $\begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}$ under the matrix A.
2. Determine the transformation of the general vector $\begin{bmatrix} 1 \\ 2 \\ 1 \end{bmatrix}$ under the matrix A.
3. Elaborate on the effects of the transformation on the vectors and the role played by the linearly dependent set of column vectors in the transformation process.
4. Use NumPy to carry out the necessary calculations step by step.
5. Visualize the transformation with the aid of Matplotlib, plotting the original vectors and their transformed counterparts in a 3D coordinate system. Include appropriate labels and a legend to differentiate the vectors before and after the transformation.


# Exercise: Matrix Transformation-- Addition or Removal of a Vector Dimension (1)

Consider the following matrices for transformation:

1. Matrix D:
$$ D = \begin{bmatrix}
4 & -1 & 2 \\
2 & 3 & 0
\end{bmatrix}
$$

2. Matrix E:
$$ E = \begin{bmatrix}
-1 & 2 & 3 \\
0 & 1 & 4 \\
2 & 0 & -1 \\
-3 & 1 & 2 \\
1 & 2 & 0
\end{bmatrix}
$$

Perform the following tasks:

For Matrix D:

1. Find the transformation of the first standard basis vector $[1, 0, 0]^T$.
2. Compute the transformation of the second standard basis vector $[0, 1, 0]^T$.
3. Determine the transformation of the third standard basis vector $[0, 0, 1]^T$.
4. Calculate the transformation of the general vector $[1, 1, 1]^T$.

For Matrix E:

1. Compute the transformation of the first standard basis vector $[1, 0, 0]^T$.
2. Find the transformation of the second standard basis vector $[0, 1, 0]^T$.
3. Determine the transformation of the third standard basis vector $[0, 0, 1]^T$.
4. Calculate the transformation of the general vector $[1, 1, 1]^T$.

Use NumPy for the necessary calculations and visualize the transformations using Matplotlib.


# Exercise: Matrix Transformation-- Addition or Removal of a Vector Dimension (2)

Consider the following matrices for transformation:

1. Matrix F:
$$ F = \begin{bmatrix}
3 & -2 & 1 \\
1 & 0 & 2
\end{bmatrix}
$$

2. Matrix G:
$$ G = \begin{bmatrix}
2 & -1 & 3 \\
0 & 4 & 2 \\
-1 & 2 & 1 \\
3 & 0 & -2 \\
1 & 2 & 0
\end{bmatrix}
$$

Perform the following tasks:

For Matrix F:

1. Find the transformation of the first standard basis vector $[1, 0, 0]^T$.
2. Compute the transformation of the second standard basis vector $[0, 1, 0]^T$.
3. Determine the transformation of the third standard basis vector $[0, 0, 1]^T$.
4. Calculate the transformation of the general vector $[1, 1, 1]^T$.

For Matrix G:

1. Compute the transformation of the first standard basis vector $[1, 0, 0]^T$.
2. Find the transformation of the second standard basis vector $[0, 1, 0]^T$.
3. Determine the transformation of the third standard basis vector $[0, 0, 1]^T$.
4. Calculate the transformation of the general vector $[1, 1, 1]^T$.

Use NumPy for the necessary calculations and visualize the transformations using Matplotlib.




# Exercise: Subspaces(1)

Consider the following set of vectors in a 3-dimensional vector space $V$:

$v_1 = \begin{bmatrix} 1 \\ 0 \\ 1  \end{bmatrix}$, $v_2 = \begin{bmatrix} 2 \\ 1 \\ 0 \end{bmatrix}$, $v_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}$

1. Determine the dimension of the vector space $V$.

2. Find the span of the set of vectors $v_1, v_2, v_3$.

3. Verify whether the set of vectors $v_1, v_2, v_3$ is linearly independent.

4. Does the set of vectors  $v_1, v_2, v_3$ span the space $V$?

5. Consider the matrix $A$:

$A = \begin{bmatrix} v_1 & v_2 & v_3 \end{bmatrix}$

where $v_1, v_2, v_3$ are the column vectors from the exercise.

  5a. What is the dimension of the vector space $R^n$ in which the column subspace is contained?
  
  5b. Determine the dimension of the column space of the matrix, $dim(C(A))$.

  5c. Find a basis for the column space of the matrix, $C(A)$.

  5d. What is the dimension of the vector space $R^n$ in which the row subspace is contained?
  
  5e. Determine the dimension of the row space of the matrix, $dim(C(A^T))$.

  5f. Find a basis for the row space of the matrix, $C(A^T)$.

  5g. What is the dimension of the vector space $R^n$ in which the null subspace is contained?
  
  5h. Determine the dimension of the null space of the matrix, $dim(N(A))$.

  5i. Find a basis for the null space of the matrix, $N(A)$.

  5j. What is the dimension of the vector space $R^n$ in which the left null subspace is contained?
  
  5k. Determine the dimension of the left null space of the matrix, $dim(N(A^T))
  
  5l. Find a basis for the left null space of the matrix, $N(A^T)$.

  5m. Check for orthogonatity between row space and null space.

  5n. Check for orthogonality between column space and left null space.


6. Consider the matrix $B$:

$B = \begin{bmatrix} v_1 & v_2 & v_3 & v_1-v_2 & v_2+v_3  \end{bmatrix}$

where $v_1, v_2, v_3$ are the column vectors from the exercise.

5a. What is the dimension of the vector space $R^n$ in which the column subspace is contained?
  
  5b. Determine the dimension of the column space of the matrix, $dim(C(B))$.

  5c. Find a basis for the column space of the matrix, $C(B)$.

  5d. What is the dimension of the vector space $R^n$ in which the row subspace is contained?
  
  5e. Determine the dimension of the row space of the matrix, $dim(C(B^T))$.

  5f. Find a basis for the row space of the matrix, $C(B^T)$.

  5g. What is the dimension of the vector space $R^n$ in which the null subspace is contained?
  
  5h. Determine the dimension of the null space of the matrix, $dim(N(B))$.

  5i. Find a basis for the null space of the matrix, $N(B)$.

  5j. What is the dimension of the vector space $R^n$ in which the left null subspace is contained?
  
  5k. Determine the dimension of the left null space of the matrix, $dim(N(B^T))
  
  5l. Find a basis for the left null space of the matrix, $N(B^T)$.

  5m. Check for orthogonatity between row space and null space.

  5n. Check for orthogonality between column space and left null space.


Use Numpy and Sympy to verify your calculations.









# Exercise: Subspaces(2)

Consider the following set of vectors in a 4-dimensional vector space $V$:

$v_1 = \begin{bmatrix} 1 \\ 0 \\ 1 \\ 2  \end{bmatrix}$, $v_2 = \begin{bmatrix} 2 \\ 1 \\ 0 \\1 \end{bmatrix}$, $v_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \\ 0 \end{bmatrix}$

1. Determine the dimension of the vector space $V$.

2. Find the span of the set of vectors $v_1, v_2, v_3$.

3. Verify whether the set of vectors $v_1, v_2, v_3$ is linearly independent.

4. Does the set of vectors  $v_1, v_2, v_3$ span the space $V$?

5. Consider the matrix $A$:

$A = \begin{bmatrix} v_1 & v_2 & v_3 \end{bmatrix}$

where $v_1, v_2, v_3$ are the column vectors from the exercise.

  5a. What is the dimension of the vector space $R^n$ in which the column subspace is contained?
  
  5b. Determine the dimension of the column space of the matrix, $dim(C(A))$.

  5c. Find a basis for the column space of the matrix, $C(A)$.

  5d. What is the dimension of the vector space $R^n$ in which the row subspace is contained?
  
  5e. Determine the dimension of the row space of the matrix, $dim(C(A^T))$.

  5f. Find a basis for the row space of the matrix, $C(A^T)$.

  5g. What is the dimension of the vector space $R^n$ in which the null subspace is contained?
  
  5h. Determine the dimension of the null space of the matrix, $dim(N(A))$.

  5i. Find a basis for the null space of the matrix, $N(A)$.

  5j. What is the dimension of the vector space $R^n$ in which the left null subspace is contained?
  
  5k. Determine the dimension of the left null space of the matrix, $dim(N(A^T))
  
  5l. Find a basis for the left null space of the matrix, $N(A^T)$.

  5m. Check for orthogonatity between row space and null space.

  5n. Check for orthogonality between column space and left null space.


6. Consider the matrix $B$:

$B = \begin{bmatrix} v_1 & v_2 & v_3 & v_1-v_2 & v_2+v_3  \end{bmatrix}$

where $v_1, v_2, v_3$ are the column vectors from the exercise.

5a. What is the dimension of the vector space $R^n$ in which the column subspace is contained?
  
  5b. Determine the dimension of the column space of the matrix, $dim(C(B))$.

  5c. Find a basis for the column space of the matrix, $C(B)$.

  5d. What is the dimension of the vector space $R^n$ in which the row subspace is contained?
  
  5e. Determine the dimension of the row space of the matrix, $dim(C(B^T))$.

  5f. Find a basis for the row space of the matrix, $C(B^T)$.

  5g. What is the dimension of the vector space $R^n$ in which the null subspace is contained?
  
  5h. Determine the dimension of the null space of the matrix, $dim(N(B))$.

  5i. Find a basis for the null space of the matrix, $N(B)$.

  5j. What is the dimension of the vector space $R^n$ in which the left null subspace is contained?
  
  5k. Determine the dimension of the left null space of the matrix, $dim(N(B^T))
  
  5l. Find a basis for the left null space of the matrix, $N(B^T)$.

  5m. Check for orthogonatity between row space and null space.

  5n. Check for orthogonality between column space and left null space.


Use Numpy and Sympy to verify your calculations.








# Exercise: Subspaces(3)

Consider the following set of vectors in a 6-dimensional vector space $V$:

$v_1 = \begin{bmatrix} 1 \\ 0 \\ 1 \\ 2 \\ 1 \\ 2 \end{bmatrix}$, $v_2 = \begin{bmatrix} 2 \\ 1 \\ 0 \\1 \\ 0 \\1 \end{bmatrix}$, $v_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \\ 0 \\ 1 \\ 0 \end{bmatrix}$

Consider the matrix $A$:

$A = \begin{bmatrix} v_1 & v_2 & v_3 \end{bmatrix}$

where $v_1, v_2, v_3$ are the column vectors from the exercise.

1. What is the dimension of the vector space $R^n$ in which the column subspace is contained?
  
2. Determine the dimension of the column space of the matrix, $dim(C(A))$.

3. Find a basis for the column space of the matrix, $C(A)$.

4. What is the dimension of the vector space $R^n$ in which the row subspace is contained?
  
5. Determine the dimension of the row space of the matrix, $dim(C(A^T))$.

6. Find a basis for the row space of the matrix, $C(A^T)$.

7. What is the dimension of the vector space $R^n$ in which the null subspace is contained?
  
8. Determine the dimension of the null space of the matrix, $dim(N(A))$.

9. Find a basis for the null space of the matrix, $N(A)$.

10. What is the dimension of the vector space $R^n$ in which the left null subspace is contained?
  
11. Determine the dimension of the left null space of the matrix, $dim(N(A^T))
  
12. Find a basis for the left null space of the matrix, $N(A^T)$.

13. Check for orthogonatity between row space and null space.

14. Check for orthogonality between column space and left null space.

15. Use Numpy and Sympy to verify your calculations.


# Exercise: Orthonormality of a Set of Vectors (1)

Consider the following set of 3-dimensional vectors:

$$\mathbf{v}_1 = \begin{bmatrix} -1 \\ 0 \\ 0 \end{bmatrix}, \quad \mathbf{v}_2 = \begin{bmatrix} 0 \\ -1 \\ 0 \end{bmatrix}, \quad \mathbf{v}_3 = \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}.$$

Perform the following tasks:

1. Verify whether the set of vectors forms an orthonormal set.
2. Utilize NumPy to carry out the necessary calculations step by step. Check the orthogonality and normality of the vectors, and then confirm if the set is orthonormal.
3. Finally, plot the vectors in a 3D coordinate system using Matplotlib to visualize their directions and lengths. Make sure to label the axes appropriately and include a legend for the vectors.

# Exercise: Orthonormality of a Set of Vectors (2)

Consider the following set of 3-dimensional vectors:

1. $\mathbf{v}_1 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix}$
2. $\mathbf{v}_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}$
3. $\mathbf{v}_3 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 0 \\ -1 \end{bmatrix}$

Perform the following tasks:

1. Verify whether the set of vectors forms an orthonormal set.
2. Utilize NumPy to carry out the necessary calculations step by step. Check the orthogonality and normality of the vectors, and then confirm if the set is orthonormal.
3. Finally, plot the vectors in a 3D coordinate system using Matplotlib to visualize their directions and lengths. Make sure to label the axes appropriately and include a legend for the vectors.

# Exercise: Orthonormality of a Set of Vectors (3)

Consider the following set of 3-dimensional vectors:

1. $\mathbf{u}_1 = \frac{1}{\sqrt{3}} \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}$
2. $\mathbf{u}_2 = \frac{1}{\sqrt{6}} \begin{bmatrix} 1 \\ -2 \\ 1 \end{bmatrix}$
3. $\mathbf{u}_3 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 0 \\ -1 \end{bmatrix}$

Perform the following tasks:

1. Verify whether the set of vectors forms an orthonormal set.
2. Utilize NumPy to carry out the necessary calculations step by step. Check the orthogonality and normality of the vectors, and then confirm if the set is orthonormal.
3. Finally, plot the vectors in a 3D coordinate system using Matplotlib to visualize their directions and lengths. Make sure to label the axes appropriately and include a legend for the vectors.

# Exercise: Rank Nullity Theorem (1)

Refer back to the Exercise: Subspaces(1).

Consider the following set of vectors in a 3-dimensional vector space $V$:

$v_1 = \begin{bmatrix} 1 \\ 0 \\ 1  \end{bmatrix}$, $v_2 = \begin{bmatrix} 2 \\ 1 \\ 0 \end{bmatrix}$, $v_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}$

$B = \begin{bmatrix} v_1 & v_2 & v_3 & v_1-v_2 & v_2+v_3  \end{bmatrix}$

where $v_1, v_2, v_3$ are the column vectors from the exercise.
  
1. Determine the dimension of the column space of the matrix, $dim(C(B))$.
  
2. Determine the dimension of the row space of the matrix, $dim(C(B^T))$.

3. Determine the dimension of the null space of the matrix, $dim(N(B))$.

4. Determine the dimension of the left null space of the matrix, $dim(N(B^T)$)

5. Do the dimensions conform with the Rank-Nullity Theorem?

6. Does the matrix conform with the Fundamental Theorem of Linear Algebra?
  







# Exercise: Rank Nullity Theorem (2)

Refer back to the Exercise: Subspaces(2).

Consider the following set of vectors in a 4-dimensional vector space $V$:

$v_1 = \begin{bmatrix} 1 \\ 0 \\ 1 \\ 2  \end{bmatrix}$, $v_2 = \begin{bmatrix} 2 \\ 1 \\ 0 \\1 \end{bmatrix}$, $v_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \\ 0 \end{bmatrix}$

$B = \begin{bmatrix} v_1 & v_2 & v_3 & v_1-v_2 & v_2+v_3  \end{bmatrix}$

where $v_1, v_2, v_3$ are the column vectors from the exercise.
  
1. Determine the dimension of the column space of the matrix, $dim(C(B))$.
  
2. Determine the dimension of the row space of the matrix, $dim(C(B^T))$.

3. Determine the dimension of the null space of the matrix, $dim(N(B))$.

4. Determine the dimension of the left null space of the matrix, $dim(N(B^T))$

5. Do the dimensions conform with the Rank-Nullity Theorem?

6. Does the matrix conform with the Fundamental Theorem of Linear Algebra?
  







# Exercise: Rank Nullity Theorem (3)

Refer back to the Exercise: Subspaces(3).

Consider the following set of vectors in a 6-dimensional vector space $V$:

$v_1 = \begin{bmatrix} 1 \\ 0 \\ 1 \\ 2 \\ 1 \\ 2 \end{bmatrix}$, $v_2 = \begin{bmatrix} 2 \\ 1 \\ 0 \\1 \\ 0 \\1 \end{bmatrix}$, $v_3 = \begin{bmatrix} 0 \\ 1 \\ 1 \\ 0 \\ 1 \\ 0 \end{bmatrix}$

Consider the matrix $A$:

$A = \begin{bmatrix} v_1 & v_2 & v_3 \end{bmatrix}$
where $v_1, v_2, v_3$ are the column vectors from the exercise.
  
1. Determine the dimension of the column space of the matrix, $dim(C(A))$.
  
2. Determine the dimension of the row space of the matrix, $dim(C(A^T))$.

3. Determine the dimension of the null space of the matrix, $dim(N(A))$.

4. Determine the dimension of the left null space of the matrix, $dim(N(A^T))$

5. Do the dimensions conform with the Rank-Nullity Theorem?

6. Does the matrix conform with the Fundamental Theorem of Linear Algebra?
  







# Exercise: Identity Matrix (1)

Consider the 4x4 matrix $ A $:

$ A = \begin{bmatrix} 2 & 1 & 0 & 3 \\ 1 & 0 & 3 & -2 \\ 4 & 2 & 1 & 5 \\ 0 & -3 & 2 & 1 \end{bmatrix} $

1. Utilize the identity matrix $ I $ to form the augmented matrix $ [A | I] $.
2. Perform row operations to transform the left side of the augmented matrix into the identity matrix.
3. Apply the same row operations to the right side of the augmented matrix to obtain the inverse of matrix $ A $, denoted as $ A^{-1} $ if it exists.
4. If $ A^{-1} $ exists verify your result by multiplying $ A $ with $ A^{-1} $ and confirm that the product is the identity matrix.
5. If $ A^{-1} $ exists linearly transform the vector $x=[1,1,1,1]^T$ with the matrix $A$ and then linearly tranform the resultant vector with the matrix $A^{-1}$. Plot the original vector as well as the transformations with the use of numpy and matplotlib.
6. Find a basis for the columns space of matirx $C(A)$.
7. Is the following set a basis for the columns space $C(A)$?

$$
\left\{ \begin{bmatrix} 1 \\ 0 \\ 0 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \\ 0 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 0 \\ 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 0 \\ 0 \\ 1 \end{bmatrix} \right\}
$$

8. Find a basis for the null space of matrix $N(A^T)$. Recall the definition of null space.

$$N(A) = \{\mathbf{x} \in \mathbb{R}^n \mid A\mathbf{x} = \mathbf{0} \} $$

9. Use numpy to confirm your calculations.


# Exercise: Identity Matrix (2)

Consider the 3x3 matrix $ A $:

$ A = \begin{bmatrix} 2 & 1 & 0\\ 1 & 0 & 1 \\ 4 & 2 & 0 \end{bmatrix} $

1. Utilize the identity matrix $ I $ to form the augmented matrix $ [A | I] $.
2. Perform row operations to transform the left side of the augmented matrix into the identity matrix.
3. Apply the same row operations to the right side of the augmented matrix to obtain the inverse of matrix $ A $, denoted as $ A^{-1} $ if it exists.
4. If $ A^{-1} $ exists verify your result by multiplying $ A $ with $ A^{-1} $ and confirm that the product is the identity matrix.
5. Find a basis for the columns space of matirx $C(A)$.
6. Is the following set a basis for the columns space $C(A)$?

$$
\left\{ \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix} \right\}
$$

7. Find a basis for the null space of matrix $N(A^T)$. Recall the definition of null space.

$$N(A) = \{\mathbf{x} \in \mathbb{R}^n \mid A\mathbf{x} = \mathbf{0} \} $$

8. Use numpy to confirm your calculations.



# Exercise: Rotation Matrix (1)

1. Find the $2 \times 2$ rotation matrix that rotates vectors in the plane by $\pi/2$ **counterclockwise**.
2. Confirm your calculations using numpy and plot the transformation of the vector $x=[3,2]^T$ using matplotlib.


# Exercise: Rotation Matrix (2)

1. Find the $2 \times 2$ rotation matrix that rotates vectors in the plane by $\pi/6$ **clockwise**.
2. Confirm your calculations using numpy and plot the transformation of the vector $x=[3,2]^T$ using matplotlib.

# Exercise: Reflection Matrix (1)

1. Find the $2 \times 2$ reflection matrix that reflects vectors **over the x axis**.
2. Confirm your calculations using numpy and plot the transformation of the vector $x=[3,2]^T$ using matplotlib.

# Exercise: Reflection Matrix (2)

1. Find the $2 \times 2$ reflection matrix that reflects vectors **over the y axis**.
2. Confirm your calculations using numpy and plot the transformation the vector $x=[3,2]^T$ using matplotlib.

# Exercise: Reflection Matrix (3)

1. Find the $2 \times 2$ reflection matrix that reflects vectors **over the x=y axis**.
2. Confirm your calculations using numpy and plot the transformation the vector $x=[3,2]^T$ using matplotlib.

# Exercise: Dilation Matrix (1)

1. Find the $2 \times 2$ dilation matrix that scale vectors by a factor of $-2$ along the $x$ and $y$ axes.
2. Confirm your calculations using numpy and plot the transformation the vector $x=[3,2]^T$ using matplotlib.



# Exercise: Shear Matrix (1)

1. Find the $2 \times 2$ shear matrix that shifts vectors horizontally ($x$-axis) by an amount $\times 3$ of its vertical coordinate ($y$-axis).
2. Confirm your calculations using numpy and plot the transformation the vector $x=[3,2]^T$ using matplotlib.


# Exercise: Shear Matrix (2)

1. Find the $2 \times 2$ shear matrix that shifts vectors vertically ($y$-axis) by an amount $\times 2$ of its horizontal coordinate ($x$-axis).
2. Confirm your calculations using numpy and plot the transformation the vector $x=[3,2]^T$ using matplotlib.


# Exercise: Determinant (1)

Consider a 2x2 matrix $ A $:

$$ A = \begin{bmatrix}
  a_{11} & a_{12} \\
  a_{21} & a_{22}
  \end{bmatrix} $$
   -
1. Write a Python function to calculate the determinant of this matrix using the formula $ \text{det}(A) = a_{11}a_{22} - a_{12}a_{21} $.
2. Test your function with different 2x2 matrices.
3. Create another function to visually represent the geometric interpretation of the determinant.
4. Test your function with different 2x2 matrices.


# Exercise: Determinant (2)

Given a 3x3 matrix $ A $:
$$ A = \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix} $$


1. Write a Python function to calculate the determinant of this matrix using the formula:
      $$ \text{det}(A) = a_{11}(a_{22}a_{33} - a_{23}a_{32}) - a_{12}(a_{21}a_{33} - a_{23}a_{31}) + a_{13}(a_{21}a_{32} - a_{22}a_{31}) $$

2. Test your functions with different 3x3 matrices.



# Exercise: Inverse of a 2x2 Matrix

Apply these steps mentiond below to find the inverse of the following matrix:

$$ A = \begin{bmatrix}
3 & 5 \\
2 & 7
\end{bmatrix} $$

___

Given a 2x2 matrix $ A $:

$$ A = \begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix} $$

1. Calculate the determinant of matrix $ A $ using the formula: $$ \text{det}(A) = a_{11}a_{22} - a_{12}a_{21} $$

2. Check if the determinant is non-zero. If $ \text{det}(A) \neq 0 $, proceed with finding the inverse.

3. Calculate the cofactors $ C_{ij} $ for each element $ a_{ij} $ using the following formulas:
   $$ C_{11} = a_{22} $$
   $$ C_{12} = -a_{21} $$
   $$ C_{21} = -a_{12} $$
   $$ C_{22} = a_{11} $$

4. Construct the cofactor matrix:
   $$ \text{Cofactor Matrix} = \begin{bmatrix}
   C_{11} & C_{12} \\
   C_{21} & C_{22}
   \end{bmatrix} = \begin{bmatrix}
   a_{22} & -a_{21} \\
   -a_{12} & a_{11}
   \end{bmatrix} $$

5. Take the transpose of the cofactor matrix to obtain the adjugate matrix $ \text{adj}(A) $:
   $$ \text{adj}(A) = \text{Cofactor Matrix}^T = \begin{bmatrix}
   a_{22} & -a_{12} \\
   -a_{21} & a_{11}
   \end{bmatrix} $$

6. Finally, find the inverse matrix $ A^{-1} $ using the formula:
   $$ A^{-1} = \frac{1}{\text{det}(A)} \cdot \text{adj}(A) $$






# Exercise: Inverse of a 2x2 Matrix (2)

Apply these steps mentiond below to find the inverse of the following matrix:

$$ A = \begin{bmatrix}
-11 & 5 \\
2 & 2
\end{bmatrix} $$

___

Given a 2x2 matrix $ A $:

$$ A = \begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix} $$

1. Calculate the determinant of matrix $ A $ using the formula: $$ \text{det}(A) = a_{11}a_{22} - a_{12}a_{21} $$

2. Check if the determinant is non-zero. If $ \text{det}(A) \neq 0 $, proceed with finding the inverse.

3. Calculate the cofactors $ C_{ij} $ for each element $ a_{ij} $ using the following formulas:
   $$ C_{11} = a_{22} $$
   $$ C_{12} = -a_{21} $$
   $$ C_{21} = -a_{12} $$
   $$ C_{22} = a_{11} $$

4. Construct the cofactor matrix:
   $$ \text{Cofactor Matrix} = \begin{bmatrix}
   C_{11} & C_{12} \\
   C_{21} & C_{22}
   \end{bmatrix} = \begin{bmatrix}
   a_{22} & -a_{21} \\
   -a_{12} & a_{11}
   \end{bmatrix} $$

5. Take the transpose of the cofactor matrix to obtain the adjugate matrix $ \text{adj}(A) $:
   $$ \text{adj}(A) = \text{Cofactor Matrix}^T = \begin{bmatrix}
   a_{22} & -a_{12} \\
   -a_{21} & a_{11}
   \end{bmatrix} $$

6. Finally, find the inverse matrix $ A^{-1} $ using the formula:
   $$ A^{-1} = \frac{1}{\text{det}(A)} \cdot \text{adj}(A) $$






## Exercise: Analyzing Rank and Null Space (1)

Consider the 3x3 matrix A given below:

$$ A = \begin{bmatrix} -3 & 5 & 3 \\ 4 & 5 & 6 \\ -7 & 8 & 7 \end{bmatrix} $$

1. Calculate the determinant of matrix A and determine whether it is singular or non-singular.

2. Find the rank of matrix A. Determine if it is a full-rank matrix or not. Explain how you arrived at this conclusion.

3. Investigate the linear dependence between the rows of matrix A. Identify the linearly dependent rows and express one row as a linear combination of others if applicable.

4. Determine the null space of matrix A. Find at least one vector belonging to the null space and explain its significance in the context of the matrix being singular.

5. If possible, find the inverse of matrix A. Explain why or why not it is possible to find the inverse based on the rank and properties of A.

6. Discuss the relationship between the rank of matrix A and the dimension of its null space. How does the rank-nullity theorem apply in this case?

7. Generalize your understanding of singular and non-singular matrices. Why is it important for a matrix to be of full rank, especially when considering the inverse and null space?

Use your findings to support your answers and provide clear explanations for each step.

## Exercise: Analyzing Rank and Null Space (2)

Consider the 5x5 matrix A given below:

$$ A = \begin{bmatrix}
1 & 2 & 3 & -4 & 5 \\
6 & 7 & 8 & 9 & 10 \\
11 & 12 & 13 & -14 & 15 \\
16 & 17 & 18 & 19 & 20 \\
21 & 22 & 23 & 24 & 25
\end{bmatrix} $$


1. Calculate the determinant of matrix A and determine whether it is singular or non-singular.

2. Find the rank of matrix A. Determine if it is a full-rank matrix or not. Explain how you arrived at this conclusion.

3. Investigate the linear dependence between the rows of matrix A. Identify the linearly dependent rows and express one row as a linear combination of others if applicable.

4. Determine the null space of matrix A. Find at least one vector belonging to the null space and explain its significance in the context of the matrix being singular.

5. If possible, find the inverse of matrix A. Explain why or why not it is possible to find the inverse based on the rank and properties of A.

6. Discuss the relationship between the rank of matrix A and the dimension of its null space. How does the rank-nullity theorem apply in this case?

7. Generalize your understanding of singular and non-singular matrices. Why is it important for a matrix to be of full rank, especially when considering the inverse and null space?

Use your findings to support your answers and provide clear explanations for each step.

# Exercise: Matrix Composition (1)

Given two matrices $A$ and $B$:

$$ A = \begin{bmatrix} 2 & 1 \\ -1 & 3 \end{bmatrix} $$

$$ B = \begin{bmatrix} 4 & 0 \\ 2 & -1 \end{bmatrix} $$

1. Calculate the composition of the two matrices, $AB$, and determine the resulting matrix's dimensions.

2. Choose an arbitrary vector $v$ in $\mathbb{R}^2$ (a vector with $2$ elements). Apply the linear transformation represented by matrix $B$ to this vector, obtaining $T1(v)$.

3. Take the result $T1(v)$ and apply the linear transformation represented by matrix $A$ to it, obtaining $T2(T1(v))$.

4. Plot the original vector $v$ and the transformed vectors $T1(v)$ and $T2(T1(v))$ separately on a graph. Use different colors for clarity.

5. Combine the two transformations by calculating the matrix product $AB$. Apply this combined transformation to the original vector $v$, obtaining $AB(v)$.

6. Plot the original vector $v$ and the transformed vector $AB(v)$ on a separate graph.

7. Compare the separate transformations $T1(v)$ and $T2(T1(v))$ with the combined transformation $AB(v)$. Discuss any similarities or differences observed in the plots.





# Exercise: Matrix Composition (2)

Given the matrix $R$:

$$ R = \begin{bmatrix}
\frac{\sqrt{2}}{2} & -\frac{\sqrt{2}}{2} \\
\frac{\sqrt{2}}{2} & \frac{\sqrt{2}}{2}
\end{bmatrix} $$

1. Calculate the composition of the $R^2$ ($R \quad \text{multipled by} \quad R$), and determine the resulting matrix's dimensions.

2. Choose an arbitrary vector $v$ in $\mathbb{R}^2$ (a vector with $2$ elements). Apply the linear transformation represented by matrix $R$ to this vector, obtaining $T1(v)$.

3. Take the result $T1(v)$ and apply the linear transformation represented by matrix $R$ to it, obtaining $T2(T1(v))$.

4. Plot the original vector $v$ and the transformed vectors $T1(v)$ and $T2(T1(v))$ separately on a graph. Use different colors for clarity.

5. Combine the two transformations by calculating the matrix product $RR$. Apply this combined transformation to the original vector $v$, obtaining $RR(v)$.

6. Plot the original vector $v$ and the transformed vector $RR(v)$ on a separate graph.

7. Compare the separate transformations $T1(v)$ and $T2(T1(v))$ with the combined transformation $RR(v)$. Discuss any similarities or differences observed in the plots.





# Exercise: Matrix Composition (3)

Given a $2x3$ matrix $A$ and a $3x4$ matrix $B$:

$$ A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix} $$

$$ B = \begin{bmatrix}
7 & 8 & 9 & 10 \\
11 & 12 & 13 & 14 \\
15 & 16 & 17 & 18
\end{bmatrix} $$


1. Calculate the composition of the two matrices, $AB$, and determine the resulting matrix's dimensions.

2. Choose an arbitrary vector $v$ in $\mathbb{R}^4$ (a vector with $4$ elements). Apply the linear transformation represented by matrix $B$ to this vector, obtaining $T1(v)$.

3. Take the result $T1(v)$ and apply the linear transformation represented by matrix $A$ to it, obtaining $T2(T1(v))$.

4. Combine the two transformations by calculating the matrix product $AB$. Apply this combined transformation to the original vector $v$, obtaining $AB(v)$.

5. Compare the separate transformations $T1(v)$ and $T2(T1(v))$ with the combined transformation $AB(v)$.





# Exercise: Scalar Multiplication Matrix (1)

Given the scalar multiplication matrix
$$
C = \begin{bmatrix}
3 & 0 & 0 \\
0 & 3 & 0 \\
0 & 0 & 3
\end{bmatrix}
$$

Let $ A $ be a 3x3 matrix
$$
A = \begin{bmatrix}
2 & 5 & 1 \\
-3 & 7 & 0 \\
4 & 1 & 6
\end{bmatrix}
$$

1. Calculate the product $ CA $.
2. Verify your calculations using numpy.



# Exercise: Scalar Multiplication Matrix (2)

Let $ A $ be a 3x3 matrix
$$
A = \begin{bmatrix}
4 & 5 & 1 \\
-1 & 7 & 0 \\
2 & 1 & 6
\end{bmatrix}
$$

1. Find the $2 \times 2$ scalar multiplication matrix $C$ that multiplies each row by -2.
2. Calculate the product $ CA $.
3. Verify your calculations using numpy.

# Exercise: Row Switching Matrix (1)

Given the row switching matrix
$$
S = \begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 0
\end{bmatrix}
$$

Let $ A $ be a 3x3 matrix
$$
A = \begin{bmatrix}
14 & 5 & 1 \\
3 & 7 & 0 \\
1 & 1 & 6
\end{bmatrix}
$$

1. Calculate the product $ SA $.
2. Verify your calculations using numpy.




# Exercise: Row Switching Matrix (2)


Let $ A $ be a 3x3 matrix
$$
A = \begin{bmatrix}
14 & 5 & 1 \\
3 & 7 & 0 \\
1 & 1 & 6
\end{bmatrix}
$$

1. Find the $3 \times 3$ row switching matrix S that reverses the row order of a matrix.
2. Calculate the product $ SA $.
3. Verify your calculations using numpy.






# Exercise: Row Addition Matrix (1)

Given the row addition matrix
$$
K = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & -1 \\
0 & 0 & 1
\end{bmatrix}
$$

Let $ A $ be a 3x3 matrix
$$
A = \begin{bmatrix}
2 & 5 & 1 \\
-3 & 7 & 0 \\
4 & 1 & 6
\end{bmatrix}
$$

1. Calculate the product $ KA $.
2. Verify your calculations using numpy.


# Exercise: Row Addition Matrix (2)

Given the row addition matrix

Let $ A $ be a 3x3 matrix
$$
A = \begin{bmatrix}
2 & 5 & 1 \\
-3 & 7 & 0 \\
4 & 1 & 6
\end{bmatrix}
$$

1. Find the #3 \times 3# row addition matrix $K$ that adds twice the values of row 1 to row 3 of a matrix.
2. Calculate the product $ KA $.
3. Verify your calculations using numpy.

# Exercise: Row Addition Matrix (3)

Given the row addition matrix

Let $ A $ be a 3x3 matrix
$$
A = \begin{bmatrix}
2 & 5 & 1 \\
-3 & 7 & 0 \\
4 & 1 & 6
\end{bmatrix}
$$

1. Find the #3 \times 3# row addition matrix $K$ that adds three times the values of row 2 to row 1 of a matrix.
2. Calculate the product $ KA $.
3. Verify your calculations using numpy.

# Exercise: Properties of Matrix Multiplication (1)

Let's consider the following matrices for the exercises:

$ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $
$ B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} $
$ C = \begin{bmatrix} 9 & 10 \\ 11 & 12 \end{bmatrix} $

**1. Associativity:**
   - Given matrices $A$, $B$, and $C$:
     - Verify associativity by calculating $(AB)C$ and $A(BC)$.
     - Check if the two results are equal.

**2. Distributivity over Addition:**
   - Given matrices $A$, $B$, and $C$:
     - Compute $A(B + C)$ and $AB + AC$.
     - Verify if the two results are equal.

**3. Non-Commutativity:**
   - Choose two matrices $A$ and $B$ of appropriate sizes.
     - Compute $AB$ and $BA$.
     - Check if $AB$ and $BA$ are equal or not.

**4. Identity Matrix:**
   - Choose a square matrix $A$ and find its identity matrix $I$.
     - Compute $IA$ and $AI$.
     - Verify if both results are equal to the original matrix $A$.

**5. Zero Matrix:**
   - Select a matrix $A$ and find the zero matrix $O$ of the same size.
     - Calculate $OA$ and $AO$.
     - Verify if both results are equal to the zero matrix $O$.

**6. Scalar Multiplication Compatibility:**
   - Pick a scalar $k$ and a matrix $A$.
     - Compute $k(A)$ and $(kA)$.
     - Check if both results are equal.

**7. Size Compatibility:**
   - Choose matrices $A$ of size $m \times n$ and $B$ of size $n \times p$.
     - Verify if the multiplication $AB$ is defined by checking the size compatibility.

**8. Matrix Powers:**
   - Choose a square matrix $A$ and calculate $A^2$ and $A^3$ using matrix multiplication.
     - Verify if $A^2$ is equal to $A \cdot A$ and $A^3$ is equal to $A \cdot A \cdot A$.

**9. Transpose of a Product:**
   - Select matrices $A$ and $B$ of appropriate sizes.
     - Compute $(AB)^T$ and $B^T A^T$.
     - Check if both results are equal.

**10. Inverse Matrices:**
    - Choose invertible matrices $A$ and $B$.
      - Compute $(AB)^{-1}$ and $B^{-1} A^{-1}$.
      - Verify if both results are equal.

**Use NumPy to verify the results.

# Exercise: Properties of Matrix Multiplication (2)

Let's consider the following matrices for the exercises:

$ A = \begin{bmatrix} 1 & 1 \\ -1 & 1 \end{bmatrix} $
$ B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} $
$ C = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $

**1. Associativity:**
   - Given matrices $A$, $B$, and $C$:
     - Verify associativity by calculating $(AB)C$ and $A(BC)$.
     - Check if the two results are equal.

**2. Distributivity over Addition:**
   - Given matrices $A$, $B$, and $C$:
     - Compute $A(B + C)$ and $AB + AC$.
     - Verify if the two results are equal.

**3. Non-Commutativity:**
   - Choose two matrices $A$ and $B$ of appropriate sizes.
     - Compute $AB$ and $BA$.
     - Check if $AB$ and $BA$ are equal or not.

**4. Identity Matrix:**
   - Choose a square matrix $A$ and find its identity matrix $I$.
     - Compute $IA$ and $AI$.
     - Verify if both results are equal to the original matrix $A$.

**5. Zero Matrix:**
   - Select a matrix $A$ and find the zero matrix $O$ of the same size.
     - Calculate $OA$ and $AO$.
     - Verify if both results are equal to the zero matrix $O$.

**6. Scalar Multiplication Compatibility:**
   - Pick a scalar $k$ and a matrix $A$.
     - Compute $k(A)$ and $(kA)$.
     - Check if both results are equal.

**7. Size Compatibility:**
   - Choose matrices $A$ of size $m \times n$ and $B$ of size $n \times p$.
     - Verify if the multiplication $AB$ is defined by checking the size compatibility.

**8. Matrix Powers:**
   - Choose a square matrix $A$ and calculate $A^2$ and $A^3$ using matrix multiplication.
     - Verify if $A^2$ is equal to $A \cdot A$ and $A^3$ is equal to $A \cdot A \cdot A$.

**9. Transpose of a Product:**
   - Select matrices $A$ and $B$ of appropriate sizes.
     - Compute $(AB)^T$ and $B^T A^T$.
     - Check if both results are equal.

**10. Inverse Matrices:**
    - Choose invertible matrices $A$ and $B$.
      - Compute $(AB)^{-1}$ and $B^{-1} A^{-1}$.
      - Verify if both results are equal.

**Use NumPy to verify the results.

# Exercise: Orthogonal Matrix (1)

For the following exercises, consider the rotation orthogonal matrix in 2D:
$$ Q = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 & 1 \\ -1 & 1 \end{bmatrix} $$

And let $ \mathbf{v} = \begin{bmatrix} 2 \\ 3 \end{bmatrix} $ be the vector.

**1. Rotation:**
   - Using the rotation matrix $ Q $ and the vector $ \mathbf{v} $, calculate the result of the rotation: $ Q \mathbf{v} $
   - Plot the transfomation of the vector $\mathbf{v}$.

**2. Orthonormal Basis Transformation:**
   - Use the rotation matrix $ Q $ to transform the standard basis vectors $ [1, 0]^T $ and $ [0, 1]^T $.
   - Calculate $ Q \begin{bmatrix} 1 \\ 0 \end{bmatrix} $ and $ Q \begin{bmatrix} 0 \\ 1 \end{bmatrix} $.
   - Verify that the results conform to orthonomal basis transformation.
   - Plot the transfomation of the standard basis vectors.

**3. Preservation of Inner Products:**
   - For vectors $ \mathbf{x} = \begin{bmatrix} 1 \\ 1 \end{bmatrix} $ and $ \mathbf{y} = \begin{bmatrix} 2 \\ 3 \end{bmatrix} $, calculate $ (Q \mathbf{x})^T (Q \mathbf{y}) $ and $ \mathbf{x}^T \mathbf{y} $.
   - Verify that the two results are equal, demonstrating the preservation of inner products.
   -Use NumPy to verify the results.






# Exercise: Orthogonal Matrix (2)

For the following exercises, consider the rotation orthogonal matrix in 2D:

$$Q = \begin{bmatrix} \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \end{bmatrix} $$

And let $ \mathbf{v} = \begin{bmatrix} -1 \\ 2 \end{bmatrix} $ be the vector.

**1. Rotation:**
   - Using the rotation matrix $ Q $ and the vector $ \mathbf{v} $, calculate the result of the rotation: $ Q \mathbf{v} $
   - Plot the transfomation of the vector $\mathbf{v}$.

**2. Orthonormal Basis Transformation:**
   - Use the rotation matrix $ Q $ to transform the standard basis vectors $ [1, 0]^T $ and $ [0, 1]^T $.
   - Calculate $ Q \begin{bmatrix} 1 \\ 0 \end{bmatrix} $ and $ Q \begin{bmatrix} 0 \\ 1 \end{bmatrix} $.
   - Verify that the results conform to orthonomal basis transformation.
   - Plot the transfomation of the standard basis vectors.

**3. Preservation of Inner Products:**
   - For vectors $ \mathbf{x} = \begin{bmatrix} 1 \\ 1 \end{bmatrix} $ and $ \mathbf{y} = \begin{bmatrix} 2 \\ 3 \end{bmatrix} $, calculate $ (Q \mathbf{x})^T (Q \mathbf{y}) $ and $ \mathbf{x}^T \mathbf{y} $.
   - Verify that the two results are equal, demonstrating the preservation of inner products.
   -Use NumPy to verify the results.






# Matrix Decomposition (1)

Consider the matrix:

$$ A = \begin{bmatrix} 2 & 4  \\ 1 & 3  \end{bmatrix} $$

1. Decompose matrix $ A $ into a matrix $$ B =  \begin{bmatrix} 2 & -1 \\ 1 & 2 \end{bmatrix}$$ and another matrix $ C $ such that $ A = CB $.


**Hint:**
   - For any matrix $ A $, $ AA^{-1} = I $.

2. After obtaining $ B $ and $ C $, verify that $ A = CB $ holds true.
3. Use NumPy to check the results of your calculations.



# Matrix Decomposition (2)

Consider the matrix:

$$ A = \begin{bmatrix} -2 & -3  \\ 4 &- 3  \end{bmatrix} $$


1. Decompose matrix $ A $ into a matrix $$ B =  \begin{bmatrix} -1 & 1 \\ 2 & 1 \end{bmatrix}$$ and another matrix $ C $ such that $ A = CB $.


**Hint:**
   - For any matrix $ A $, $ AA^{-1} = I $.

2. After obtaining $ B $ and $ C $, verify that $ A = CB $ holds true.
3. Use NumPy to check the results of your calculations.
4. Consider the matrix  $$ I =  \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$$. Perform the transformation $B\cdot I.$ What happens to the standard basis vectors?
5. Now perform the transformation $C\cdot B \cdot I$. What happens to the standard basis vectors after combined linear transformation?
6. Interpret the linear transformation of $A \cdot v$ where vector $v = [2,3]^T$. Plot the transformation.



# Matrix Decomposition (3)

Consider the matrix:

$$ A = \begin{bmatrix} -2 & -3  \\ 2 &- 3  \end{bmatrix} $$


1. Decompose matrix $ A $ into an orthogonal matrix $$ B =  \begin{bmatrix} -1 & 1 \\ 1 & 1 \end{bmatrix}$$ and another matrix $ C $ such that $ A = CB $.


**Hint:**
   - For any matrix $ A $, $ AA^{-1} = I $.
   - For an orthogonal matrix $ Q $, $ Q^{-1} = Q^T $.

2. After obtaining $ B $ and $ C $, verify that $ A = CB $ holds true.
3. Use NumPy to check the results of your calculations.
4. Consider the matrix  $$ I =  \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$$. Perform the transformation $B\cdot I.$ What happens to the standard basis vectors?
5. Now perform the transformation $C\cdot B \cdot I$. What happens to the standard basis vectors after combined linear transformation?
6. Interpret the linear transformation of $A \cdot v$ where vector $v = [2,3]^T$. Plot the transformation.
7. Perform $AA^T$ using two methods, first taking the original matrix $A$, then using the decomposition $A = BC$. Which method is comutationally less intensive? **Hint: $(BC)^T = C^TB^T$**



# Exercise: LU Decomposition (1)

Consider the matrix $ A $:
$$ A = \begin{bmatrix} 2 & 4 & 1\\ 1 & 3 & 2 \\ -1 & 3 & 7 \end{bmatrix} $$

Perform LU decomposition on matrix $ A $ and express it as $ A = LU $.


# Exercise: LU Decomposition (2)

Given the linear system $ Ax = b $, where:
$$
A = \begin{bmatrix} -2 & 3  & 6 \\ 1 & 3 & 2 \\ -1 & 3 & -2 \end{bmatrix}
$$
$$ b= \begin{bmatrix} 10 \\ 7 \\ -1 \end{bmatrix} $$

Use LU decomposition to solve for $ x $.

**Hint:** After obtaining $ A = LU $, let $ Ux = y $ and solve for $ y $ using forward substitution. Then, solve for $ x $ using back substitution.


# Exercise: LU Decompsition (3)

Consider a general $ 3 \times 3 $ matrix $ A $:
$$A = \begin{bmatrix} a & b & c \\ d & e & f \\ g & h & i \end{bmatrix} $$

Perform LU decomposition on matrix $ A $ and express it as $ A = LU $.



# LU Decomposition (4)

Write a Python function to perform LU decomposition on a given square matrix. Test your function with different matrices.






# Exercise: QR Decomposition (1)

Given the matrix A:
   $$A = \begin{bmatrix} 3 & 1 \\ 4 & 1 \\ \end{bmatrix} $$
   
Calculate the QR decomposition of A.


# Exercise: QR decomposition (2)
Suppose we have the following system of linear equations:

$$ \begin{align*}
2x + y  &= 8 \\
x + 3y  &= 11 \\
\end{align*} $$


**Hint:**
The QR decomposition of A is given by:
$A=QR$

$Ax=b$

$QRx=b$

Since $Q^T⋅Q=I$, we can multiply both sides by $Q^T$ to get:

$Rx=QTb$


# Exercise: QR Decomposition (3)

Given the matrix C:
  $$ C = \begin{bmatrix} 1 & -1 & 3 \\ 2 & 1 & 2 \end{bmatrix} $$

Calculate the QR decomposition of C and verify the orthogonality property $Q^T \cdot Q = I$.






# Exercise: QR Decomposition (4)

Consider the matrix B:
 $$ B = \begin{bmatrix} 1 & 0.999 \\ 0.999 & 1 \end{bmatrix} $$

Compare the solutions obtained by directly solving $ Bx = \begin{bmatrix} 2 \\ 2 \end{bmatrix} $ and solving the system after performing QR decomposition on matrix B.


# Exercise: QR Decomposition (5)

Implement a Python function to perform QR decomposition of a given matrix. Test your function with a few matrices and verify the results.


In [ ]:
import numpy as np


B = np.array([[3, 0, -2],
              [1, 1, 0],
              [0, 1, 1]])


D = np.array([[2, 0, 0],
              [0, 1, 0],
              [0, 0, 3]])

print(B)
print("mean B axis 0", np.mean(B, axis=0))
print("mean B axis 1", np.mean(B, axis=1))
print(np.linalg.inv(B))
print(np.linalg.det(B))

A = B@D@np.linalg.inv(B)
print(A)
# Define the matrix A
# A = np.array([[4, 1, 0],
#               [2, 5, 1],
#               [0, 2, 3]])

# Eigen decomposition
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print eigenvalues and eigenvectors
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

# Verify the eigen decomposition
Lambda = np.diag(eigenvalues)
V = eigenvectors

reconstructed_A = np.dot(np.dot(V, Lambda), np.linalg.inv(V))

print("\nReconstructed A from Eigen Decomposition:")
print(reconstructed_A)


[[ 3  0 -2]
 [ 1  1  0]
 [ 0  1  1]]
mean B axis 0 [ 1.33333333  0.66666667 -0.33333333]
mean B axis 1 [0.33333333 0.66666667 0.66666667]
[[ 1. -2.  2.]
 [-1.  3. -2.]
 [ 1. -3.  3.]]
1.0000000000000002
[[-4.4408921e-16  6.0000000e+00 -6.0000000e+00]
 [ 1.0000000e+00 -1.0000000e+00  2.0000000e+00]
 [ 2.0000000e+00 -6.0000000e+00  7.0000000e+00]]
Eigenvalues:
[3. 2. 1.]

Eigenvectors:
[[-8.94427191e-01  9.48683298e-01 -4.64580094e-15]
 [-1.69995052e-16  3.16227766e-01 -7.07106781e-01]
 [ 4.47213595e-01 -4.09430021e-16 -7.07106781e-01]]

Reconstructed A from Eigen Decomposition:
[[-2.90402307e-16  6.00000000e+00 -6.00000000e+00]
 [ 1.00000000e+00 -1.00000000e+00  2.00000000e+00]
 [ 2.00000000e+00 -6.00000000e+00  7.00000000e+00]]


In [ ]:
import numpy as np

A = np.array([
    [0, 6, -6],
    [1, -1, 2],
    [2, -6, 7]
])


# Eigen decomposition
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print eigenvalues and eigenvectors
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

# Verify the eigen decomposition
Lambda = np.diag(eigenvalues)
V = eigenvectors

reconstructed_A = np.dot(np.dot(V, Lambda), np.linalg.inv(V))

print("\nReconstructed A from Eigen Decomposition:")
print(reconstructed_A)


Eigenvalues:
[3. 2. 1.]

Eigenvectors:
[[ 8.94427191e-01 -9.48683298e-01  4.95044363e-15]
 [-2.40897415e-16 -3.16227766e-01 -7.07106781e-01]
 [-4.47213595e-01  6.65323785e-16 -7.07106781e-01]]

Reconstructed A from Eigen Decomposition:
[[-2.45399312e-15  6.00000000e+00 -6.00000000e+00]
 [ 1.00000000e+00 -1.00000000e+00  2.00000000e+00]
 [ 2.00000000e+00 -6.00000000e+00  7.00000000e+00]]


In [ ]:
import sympy as sp

# Define the symbols
x, y, z = sp.symbols('x y z')

# Define the augmented matrix
A = sp.Matrix([
    [-3, 6, -6],
    [1, -4, 2],
    [2, -6, 4]
])


# Use the rref method to find the Reduced Row Echelon Form
rref_matrix, pivot_columns = A.rref()

# Print the Reduced Row Echelon Form
print("Reduced Row Echelon Form:")
print(rref_matrix)

# Find the null space
null_space_vectors = A.nullspace()

# Print the null space vectors
print("\nNull Space Vectors:")
for vector in null_space_vectors:
    print(vector)


Reduced Row Echelon Form:
Matrix([[1, 0, 2], [0, 1, 0], [0, 0, 0]])

Null Space Vectors:
Matrix([[-2], [0], [1]])


In [ ]:
import numpy as np

# Step 1: Generate a random 5x5 matrix
np.random.seed(42)
A = np.random.rand(5, 5)

# Step 2: Mean centering
mean_A = np.mean(A, axis=0)
A_centered = A - mean_A

# Step 3: Covariance matrix
C = np.cov(A_centered, rowvar=False)

# Step 4: Eigen decomposition
eigenvalues, eigenvectors = np.linalg.eig(C)

# Step 5: Principal components
# Sort eigenvalues and corresponding eigenvectors in descending order
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

# Choose the top k=2 eigenvectors
k = 2
P = eigenvectors[:, :k]

# Step 6: Projection
Y = np.dot(A_centered, P)

# Verify with library function for PCA calculation
from sklearn.decomposition import PCA

# Create a PCA object
pca = PCA(n_components=k)

# Fit and transform the original data
Y_sklearn = pca.fit_transform(A)

# Print the results
print("Original Matrix A:")
print(A)
print("\nMean-centered Matrix A:")
print(A_centered)
print("\nCovariance Matrix C:")
print(C)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)
print("\nTop 2 Principal Components P:")
print(P)
print("\nProjected Matrix Y:")
print(Y)
print("\nProjected Matrix Y (using library function):")
print(Y_sklearn)


Original Matrix A:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]

Mean-centered Matrix A:
[[ 0.10526481  0.46622553  0.08249118  0.15657459 -0.20262442]
 [-0.11328079 -0.42640516  0.21667338  0.15903112  0.34942952]
 [-0.24869081  0.48542108  0.18293988 -0.22974478 -0.17681809]
 [-0.0858708  -0.18024653 -0.12474633 -0.01013888 -0.06741392]
 [ 0.34257759 -0.34499491 -0.35735811 -0.07572205  0.09742692]]

Covariance Matrix C:
[[ 5.26233837e-02 -3.15121798e-02 -4.32669484e-02  7.63299934e-03
   5.55633271e-03]
 [-3.15121798e-02  1.96582884e-01  4.51608857e-02 -1.95960897e-02
  -8.76897813e-02]
 [-4.32669484e-02  4.51608857e-02  5.76214044e-02  8.41725674e-03
   6.09013477e-05]
 [ 7.63299934e-03 -1.95960897e-02  8.41725674e-03  2.71064475e-02
   1.4